/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Subham
 */

package discountpricecalculator;

public class mainInterface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainInterface.class.getName());

    /**
     * Creates new form mainInterface
     */
    public mainInterface() {
        initComponents();

            // Calculate Button - compute total and discounted price
    calculate.addActionListener(e -> {
        try {
            double[] prices = {
                Double.parseDouble(item1price.getText()),
                Double.parseDouble(item2price.getText()),
                Double.parseDouble(item3price.getText()),
                Double.parseDouble(item4price.getText())
            };

            int[] quantities = {
                Integer.parseInt(item1quantity.getText()),
                Integer.parseInt(item2quantity.getText()),
                Integer.parseInt(item3quantity.getText()),
                Integer.parseInt(item4quantity.getText())
            };

            double total = 0;
            for (int i = 0; i < 4; i++) {
                total += prices[i] * quantities[i];
            }

            double discountPercent = Double.parseDouble(discountvalue.getText());
            double discountAmount = total * discountPercent / 100;
            double finalPrice = total - discountAmount;

            totalprice.setText("Total Price : " + String.format("%.2f", total));
            discount_totalprice.setText("After Discount, Total Price : " + String.format("%.2f", finalPrice));
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid numeric values.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    });

    // Clear Button - reset all fields
    clear.addActionListener(e -> {
        item1price.setText("");
        item2price.setText("");
        item3price.setText("");
        item4price.setText("");

        item1quantity.setText("");
        item2quantity.setText("");
        item3quantity.setText("");
        item4quantity.setText("");

        discountvalue.setText("");

        totalprice.setText("Total Price :");
        discount_totalprice.setText("After Discount, Total Price :");
    });

    // Cancel Button - go back to WelcomePage
    cancel.addActionListener(e -> {
        new WelcomePage().setVisible(true); // Navigate back
        dispose(); // Close mainInterface
    });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        mainTitle = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        quantity = new javax.swing.JLabel();
        item1 = new javax.swing.JLabel();
        item1price = new javax.swing.JTextField();
        item1quantity = new javax.swing.JTextField();
        item2 = new javax.swing.JLabel();
        item2price = new javax.swing.JTextField();
        item2quantity = new javax.swing.JTextField();
        item3 = new javax.swing.JLabel();
        item3price = new javax.swing.JTextField();
        item3quantity = new javax.swing.JTextField();
        item4 = new javax.swing.JLabel();
        item4price = new javax.swing.JTextField();
        item4quantity = new javax.swing.JTextField();
        discount = new javax.swing.JLabel();
        discountvalue = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        totalprice = new javax.swing.JLabel();
        discount_totalprice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 0, 153));

        mainTitle.setBackground(new java.awt.Color(255, 255, 255));
        mainTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(255, 255, 255));
        mainTitle.setText("Welcome To");

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Discount Price Calculator");

        price.setBackground(new java.awt.Color(255, 255, 255));
        price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setText("Price");

        quantity.setBackground(new java.awt.Color(255, 255, 255));
        quantity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        quantity.setForeground(new java.awt.Color(255, 255, 255));
        quantity.setText("Quantity");

        item1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        item1.setForeground(new java.awt.Color(255, 255, 255));
        item1.setText("Item 1 :");

        item2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        item2.setForeground(new java.awt.Color(255, 255, 255));
        item2.setText("Item 2 :");

        item3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        item3.setForeground(new java.awt.Color(255, 255, 255));
        item3.setText("Item 3 :");

        item4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        item4.setForeground(new java.awt.Color(255, 255, 255));
        item4.setText("Item 4 :");

        discount.setBackground(new java.awt.Color(255, 255, 255));
        discount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        discount.setForeground(new java.awt.Color(255, 255, 255));
        discount.setText("Enter your Discount -");

        calculate.setText("Calculate");

        clear.setText("Clear");

        cancel.setText("Cancel");

        totalprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalprice.setForeground(new java.awt.Color(255, 255, 255));
        totalprice.setText("Total Price :");

        discount_totalprice.setBackground(new java.awt.Color(255, 255, 255));
        discount_totalprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        discount_totalprice.setForeground(new java.awt.Color(255, 255, 255));
        discount_totalprice.setText("After Discount, Total Price :");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(price)
                .addGap(76, 76, 76)
                .addComponent(quantity)
                .addGap(52, 52, 52))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(item2)
                                    .addComponent(item3)
                                    .addComponent(item4))
                                .addGap(62, 62, 62)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(item3price, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(item2price)
                                    .addComponent(item4price))
                                .addGap(64, 64, 64))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(discount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(discountvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(item1)
                                .addGap(62, 62, 62)
                                .addComponent(item1price, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(item2quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(item3quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(item4quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(item1quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(mainTitle))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(cancel)
                        .addGap(54, 54, 54)
                        .addComponent(calculate)
                        .addGap(47, 47, 47)
                        .addComponent(clear))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalprice)
                            .addComponent(discount_totalprice))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(mainTitle)
                .addGap(18, 18, 18)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price)
                    .addComponent(quantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item1)
                    .addComponent(item1price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item1quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item2price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item2)
                    .addComponent(item2quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item3price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item3quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item3))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item4price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item4quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item4))
                .addGap(30, 30, 30)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discount)
                    .addComponent(discountvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculate)
                    .addComponent(clear)
                    .addComponent(cancel))
                .addGap(18, 18, 18)
                .addComponent(totalprice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(discount_totalprice)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainInterface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton calculate;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    private javax.swing.JLabel discount;
    private javax.swing.JLabel discount_totalprice;
    private javax.swing.JTextField discountvalue;
    private javax.swing.JLabel item1;
    private javax.swing.JTextField item1price;
    private javax.swing.JTextField item1quantity;
    private javax.swing.JLabel item2;
    private javax.swing.JTextField item2price;
    private javax.swing.JTextField item2quantity;
    private javax.swing.JLabel item3;
    private javax.swing.JTextField item3price;
    private javax.swing.JTextField item3quantity;
    private javax.swing.JLabel item4;
    private javax.swing.JTextField item4price;
    private javax.swing.JTextField item4quantity;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JLabel price;
    private javax.swing.JLabel quantity;
    private javax.swing.JLabel title;
    private javax.swing.JLabel totalprice;
    // End of variables declaration//GEN-END:variables
}
